version: '3.5'
services:
  api1: # API - Instância 01
    image: rinha-glauco
    hostname: api1
    network_mode: host
    environment:
      API_PORT: 8001
      WORKERS: 2
    command: python run_api.py
    depends_on:
      - postgresdb
      - redis 
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '0.4GB'

  api2: # API - Instância 01
    image: rinha-glauco
    hostname: api2
    network_mode: host
    environment:
      API_PORT: 8002
      WORKERS: 2
    command: python run_api.py
    depends_on:
      - postgresdb
      - api1
      - redis 
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '0.4GB'

  agent: # AGENT
    image: rinha-glauco
    hostname: agent
    network_mode: host
    command: python run_agent.py
    depends_on:
      - postgresdb
      - api1
      - api2
      - redis 
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.2GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    hostname: nginx
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.1GB'

  postgresdb: # Banco de dados
    image: postgres
    container_name: postgresdb
    hostname: postgresdb
    network_mode: host
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c max_connections=400 -c log_min_messages=FATAL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.29'
          memory: '0.5GB'


  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    network_mode: host
    command: redis-server --save "" --appendonly no --maxclients 10000
    deploy:
      resources:
        limits:
          cpus: '0.06'
          memory: '0.1GB'