version: '3.5'
services:
  api1: # API - Instância 01
    image: rinha-glauco:1.0
    hostname: api1
    network_mode: host
    environment:
      API_PORT: 8001
      LOG_LEVEL: DEBUG
      WORKERS: 2
    depends_on:
      - postgresdb
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2: # API - Instância 01
    image: rinha-glauco:1.0
    hostname: api2
    network_mode: host
    environment:
      API_PORT: 8002
      LOG_LEVEL: DEBUG
      WORKERS: 2
    depends_on:
      - postgresdb
      - api1
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    hostname: nginx
    network_mode: host
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  postgresdb: # Banco de dados
    image: postgres
    container_name: postgresdb
    hostname: postgresdb
    network_mode: host
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: banco
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'